name: Notify users based on issue labels

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
             recipients: |
                  cluster/ocp4= @cluster/ocp4-admin
                  cluster/ocp3= @cluster/ocp3-admin
                  cluster/ocp5= @cluster/ocp5-admin
                  cluster/rhacm= @cluster/rhacm-admin
